variable "cidr_block_vpc" {}
variable "stage" {}
variable "project" {}
variable "cidr_block_public_1a" {}
variable "cidr_block_public_1c" {}
variable "cidr_block_private_1a" {}
variable "cidr_block_private_1c" {}
variable "az_1a" {}
variable "az_1c" {}