variable "project" {}
variable "stage" {}
variable "public_1a" {}
variable "public_1c" {}
variable "ecs_task_execution_role" {}
variable "sg_for_ecs" {}
variable "tg" {}
variable "container_port" {}
variable "region" {}
variable "env_secret_manager" {}
variable "ecr_repo_uri" {}